// AAROGYAM Mock Data - Comprehensive Healthcare Dataset

export const DEMO_CREDENTIALS = {
  patient: { email: "patient@aarogyam.com", password: "password123", role: "patient" },
  doctor: { email: "doctor@aarogyam.com", password: "password123", role: "doctor" },
  admin: { email: "admin@aarogyam.com", password: "password123", role: "admin" },
};

export const patients = [
  {
    id: "AAR-001",
    name: "Arjun Sharma",
    age: 34,
    gender: "Male",
    dob: "1990-03-15",
    bloodType: "O+",
    phone: "+91-9876543210",
    email: "arjun.sharma@email.com",
    address: "12, MG Road, Mumbai, Maharashtra 400001",
    emergencyContact: { name: "Priya Sharma", relation: "Wife", phone: "+91-9876543211" },
    allergies: ["Penicillin", "Sulfa drugs"],
    chronicConditions: ["Hypertension", "Type 2 Diabetes"],
    photo: null,
    healthScore: 72,
    lastVisit: "2024-01-15",
    insurance: "Star Health - SH-2024-98765",
  },
  {
    id: "AAR-002",
    name: "Priya Mehta",
    age: 28,
    gender: "Female",
    dob: "1996-07-22",
    bloodType: "B+",
    phone: "+91-9876543220",
    email: "priya.mehta@email.com",
    address: "45, Koregaon Park, Pune, Maharashtra 411001",
    emergencyContact: { name: "Ravi Mehta", relation: "Husband", phone: "+91-9876543221" },
    allergies: ["Aspirin"],
    chronicConditions: [],
    photo: null,
    healthScore: 91,
    lastVisit: "2024-02-08",
    insurance: "HDFC Ergo - HE-2024-12345",
  },
  {
    id: "AAR-003",
    name: "Rajesh Kumar",
    age: 52,
    gender: "Male",
    dob: "1972-11-08",
    bloodType: "A+",
    phone: "+91-9876543230",
    email: "rajesh.kumar@email.com",
    address: "78, Anna Nagar, Chennai, Tamil Nadu 600040",
    emergencyContact: { name: "Sunita Kumar", relation: "Wife", phone: "+91-9876543231" },
    allergies: ["Latex", "Ibuprofen"],
    chronicConditions: ["Coronary Artery Disease", "Hypertension"],
    photo: null,
    healthScore: 58,
    lastVisit: "2024-01-28",
    insurance: "New India Assurance - NIA-2024-56789",
  },
  {
    id: "AAR-004",
    name: "Anjali Singh",
    age: 41,
    gender: "Female",
    dob: "1983-05-12",
    bloodType: "AB+",
    phone: "+91-9876543240",
    email: "anjali.singh@email.com",
    address: "23, Banjara Hills, Hyderabad, Telangana 500034",
    emergencyContact: { name: "Vikram Singh", relation: "Husband", phone: "+91-9876543241" },
    allergies: [],
    chronicConditions: ["Asthma"],
    photo: null,
    healthScore: 79,
    lastVisit: "2024-02-14",
    insurance: "Bajaj Allianz - BA-2024-34567",
  },
  {
    id: "AAR-005",
    name: "Suresh Nair",
    age: 63,
    gender: "Male",
    dob: "1961-09-03",
    bloodType: "O-",
    phone: "+91-9876543250",
    email: "suresh.nair@email.com",
    address: "56, Kozhikode Road, Kochi, Kerala 682001",
    emergencyContact: { name: "Meera Nair", relation: "Daughter", phone: "+91-9876543251" },
    allergies: ["Morphine", "Codeine"],
    chronicConditions: ["Type 2 Diabetes", "CKD Stage 3"],
    photo: null,
    healthScore: 45,
    lastVisit: "2024-01-20",
    insurance: "Oriental Insurance - OI-2024-78901",
  },
];

export const doctors = [
  {
    id: "DOC-001",
    name: "Dr. Kavitha Reddy",
    specialization: "Internal Medicine",
    qualification: "MBBS, MD (Internal Medicine)",
    hospital: "Apollo Hospitals",
    city: "Hyderabad",
    experience: 15,
    registrationNo: "MCI-2024-HYD-001",
    email: "kavitha.reddy@aarogyam.com",
    phone: "+91-9123456789",
    availableDays: ["Monday", "Wednesday", "Friday"],
    consultationFee: 800,
  },
  {
    id: "DOC-002",
    name: "Dr. Arun Patel",
    specialization: "Cardiology",
    qualification: "MBBS, MD, DM (Cardiology)",
    hospital: "Kokilaben Hospital",
    city: "Mumbai",
    experience: 20,
    registrationNo: "MCI-2024-MUM-002",
    email: "arun.patel@aarogyam.com",
    phone: "+91-9123456790",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    consultationFee: 1500,
  },
];

export const medicalHistory = [
  {
    id: "MH-001",
    patientId: "AAR-001",
    date: "2024-01-15",
    type: "Consultation",
    diagnosis: "Hypertension - Grade 1",
    doctor: "Dr. Kavitha Reddy",
    hospital: "Apollo Hospitals",
    symptoms: ["Headache", "Dizziness", "Shortness of breath"],
    notes: "BP 145/90 mmHg. Advised lifestyle modification and started antihypertensives.",
    prescription: "PRS-001",
    severity: "moderate",
  },
  {
    id: "MH-002",
    patientId: "AAR-001",
    date: "2023-11-20",
    type: "Lab Report",
    diagnosis: "HbA1c - 7.2% (Controlled Diabetes)",
    doctor: "Dr. Arun Patel",
    hospital: "Kokilaben Hospital",
    symptoms: ["Fatigue", "Frequent urination"],
    notes: "HbA1c improved from 8.1% to 7.2%. Continue current medication.",
    prescription: null,
    severity: "mild",
  },
  {
    id: "MH-003",
    patientId: "AAR-001",
    date: "2023-08-05",
    type: "Emergency",
    diagnosis: "Acute Gastroenteritis",
    doctor: "Dr. Pradeep Kumar",
    hospital: "Lilavati Hospital",
    symptoms: ["Vomiting", "Diarrhea", "Fever 102°F"],
    notes: "Admitted for 2 days. IV fluids administered. Full recovery.",
    prescription: "PRS-002",
    severity: "high",
  },
  {
    id: "MH-004",
    patientId: "AAR-001",
    date: "2023-05-12",
    type: "Routine Checkup",
    diagnosis: "Annual Health Screening",
    doctor: "Dr. Kavitha Reddy",
    hospital: "Apollo Hospitals",
    symptoms: [],
    notes: "All vitals normal. Cholesterol slightly elevated - 210 mg/dL. Diet counseling given.",
    prescription: null,
    severity: "low",
  },
  {
    id: "MH-005",
    patientId: "AAR-001",
    date: "2022-12-01",
    type: "Surgery",
    diagnosis: "Appendectomy",
    doctor: "Dr. Suresh Iyer",
    hospital: "Breach Candy Hospital",
    symptoms: ["Severe abdominal pain", "Nausea", "Fever"],
    notes: "Emergency appendectomy performed laparoscopically. Discharged after 3 days.",
    prescription: "PRS-003",
    severity: "high",
  },
];

export const prescriptions = [
  {
    id: "PRS-001",
    patientId: "AAR-001",
    patientName: "Arjun Sharma",
    doctorId: "DOC-001",
    doctorName: "Dr. Kavitha Reddy",
    date: "2024-01-15",
    diagnosis: "Hypertension - Grade 1, Type 2 Diabetes",
    medications: [
      {
        name: "Amlodipine",
        dosage: "5mg",
        frequency: "Once daily",
        duration: "30 days",
        route: "Oral",
        instructions: "Take in the morning with water",
      },
      {
        name: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "30 days",
        route: "Oral",
        instructions: "Take after meals",
      },
      {
        name: "Aspirin",
        dosage: "75mg",
        frequency: "Once daily",
        duration: "30 days",
        route: "Oral",
        instructions: "Take after breakfast",
      },
    ],
    advice: "Low salt diet, regular exercise 30 min/day, monitor BP daily",
    followUp: "2024-02-15",
    hospital: "Apollo Hospitals",
    hospitalAddress: "Jubilee Hills, Hyderabad - 500033",
    registrationNo: "MCI-2024-HYD-001",
  },
  {
    id: "PRS-002",
    patientId: "AAR-001",
    patientName: "Arjun Sharma",
    doctorId: "DOC-001",
    doctorName: "Dr. Pradeep Kumar",
    date: "2023-08-05",
    diagnosis: "Acute Gastroenteritis",
    medications: [
      {
        name: "ORS Solution",
        dosage: "1 sachet in 1L water",
        frequency: "4 times daily",
        duration: "5 days",
        route: "Oral",
        instructions: "Sip slowly throughout the day",
      },
      {
        name: "Ondansetron",
        dosage: "4mg",
        frequency: "Every 8 hours",
        duration: "3 days",
        route: "Oral",
        instructions: "For nausea/vomiting",
      },
      {
        name: "Norfloxacin",
        dosage: "400mg",
        frequency: "Twice daily",
        duration: "5 days",
        route: "Oral",
        instructions: "Take on empty stomach",
      },
    ],
    advice: "Light diet, plenty of fluids, avoid spicy food for 2 weeks",
    followUp: "2023-08-12",
    hospital: "Lilavati Hospital",
    hospitalAddress: "Bandra West, Mumbai - 400050",
    registrationNo: "MCI-2024-MUM-045",
  },
];

export const vaccinations = [
  {
    id: "VAC-001",
    patientId: "AAR-001",
    name: "COVID-19 (Covishield)",
    dose: "Booster",
    date: "2023-07-15",
    nextDue: null,
    administeredBy: "Dr. Kavitha Reddy",
    batchNo: "COVI-2023-BN45678",
    status: "completed",
  },
  {
    id: "VAC-002",
    patientId: "AAR-001",
    name: "Influenza (Flu Shot)",
    dose: "Annual",
    date: "2024-01-10",
    nextDue: "2025-01-10",
    administeredBy: "Nurse Sunita",
    batchNo: "FLU-2024-AN12345",
    status: "completed",
  },
  {
    id: "VAC-003",
    patientId: "AAR-001",
    name: "Hepatitis B",
    dose: "3rd Dose",
    date: "2023-09-20",
    nextDue: null,
    administeredBy: "Dr. Arun Patel",
    batchNo: "HEPB-2023-3D67890",
    status: "completed",
  },
  {
    id: "VAC-004",
    patientId: "AAR-001",
    name: "Typhoid",
    dose: "Booster",
    date: null,
    nextDue: "2024-03-15",
    administeredBy: null,
    batchNo: null,
    status: "due",
  },
  {
    id: "VAC-005",
    patientId: "AAR-001",
    name: "Pneumococcal (PCV)",
    dose: "1st Dose",
    date: null,
    nextDue: "2024-04-01",
    administeredBy: null,
    batchNo: null,
    status: "upcoming",
  },
];

export const appointments = [
  {
    id: "APT-001",
    patientId: "AAR-001",
    patientName: "Arjun Sharma",
    doctorId: "DOC-001",
    doctorName: "Dr. Kavitha Reddy",
    specialization: "Internal Medicine",
    hospital: "Apollo Hospitals",
    date: "2024-02-20",
    time: "10:00 AM",
    type: "Follow-up",
    status: "confirmed",
    notes: "BP follow-up and diabetes review",
    fee: 800,
  },
  {
    id: "APT-002",
    patientId: "AAR-001",
    patientName: "Arjun Sharma",
    doctorId: "DOC-002",
    doctorName: "Dr. Arun Patel",
    specialization: "Cardiology",
    hospital: "Kokilaben Hospital",
    date: "2024-03-05",
    time: "02:30 PM",
    type: "Consultation",
    status: "pending",
    notes: "Cardiac evaluation for chest pain episodes",
    fee: 1500,
  },
  {
    id: "APT-003",
    patientId: "AAR-001",
    patientName: "Arjun Sharma",
    doctorId: "DOC-001",
    doctorName: "Dr. Kavitha Reddy",
    specialization: "Internal Medicine",
    hospital: "Apollo Hospitals",
    date: "2024-01-15",
    time: "11:00 AM",
    type: "Consultation",
    status: "completed",
    notes: "Initial consultation for hypertension management",
    fee: 800,
  },
];

export const labReports = [
  {
    id: "LAB-001",
    patientId: "AAR-001",
    date: "2024-01-14",
    name: "Complete Blood Count (CBC)",
    orderedBy: "Dr. Kavitha Reddy",
    lab: "Apollo Diagnostics",
    status: "completed",
    results: [
      { test: "Hemoglobin", value: "13.8", unit: "g/dL", reference: "13.0-17.0", status: "normal" },
      { test: "WBC Count", value: "7.2", unit: "×10³/µL", reference: "4.0-11.0", status: "normal" },
      { test: "Platelet Count", value: "245", unit: "×10³/µL", reference: "150-400", status: "normal" },
      { test: "RBC Count", value: "4.8", unit: "×10⁶/µL", reference: "4.5-5.5", status: "normal" },
    ],
  },
  {
    id: "LAB-002",
    patientId: "AAR-001",
    date: "2023-11-20",
    name: "HbA1c & Lipid Profile",
    orderedBy: "Dr. Arun Patel",
    lab: "SRL Diagnostics",
    status: "completed",
    results: [
      { test: "HbA1c", value: "7.2", unit: "%", reference: "<6.5", status: "high" },
      { test: "Total Cholesterol", value: "210", unit: "mg/dL", reference: "<200", status: "high" },
      { test: "LDL", value: "128", unit: "mg/dL", reference: "<100", status: "high" },
      { test: "HDL", value: "48", unit: "mg/dL", reference: ">40", status: "normal" },
      { test: "Triglycerides", value: "156", unit: "mg/dL", reference: "<150", status: "high" },
    ],
  },
  {
    id: "LAB-003",
    patientId: "AAR-001",
    date: "2024-01-14",
    name: "Kidney Function Test (KFT)",
    orderedBy: "Dr. Kavitha Reddy",
    lab: "Apollo Diagnostics",
    status: "completed",
    results: [
      { test: "Creatinine", value: "1.1", unit: "mg/dL", reference: "0.7-1.3", status: "normal" },
      { test: "BUN", value: "18", unit: "mg/dL", reference: "7-20", status: "normal" },
      { test: "eGFR", value: "72", unit: "mL/min/1.73m²", reference: ">60", status: "normal" },
    ],
  },
];

// Disease surveillance data for Indian cities
export const diseaseData = [
  // Mumbai
  { id: "DS-001", city: "Mumbai", state: "Maharashtra", lat: 19.076, lng: 72.877, disease: "Dengue", cases: 245, deaths: 3, date: "2024-01-15", severity: "high", ageGroup: "15-44" },
  { id: "DS-002", city: "Mumbai", state: "Maharashtra", lat: 19.076, lng: 72.877, disease: "Malaria", cases: 128, deaths: 1, date: "2024-01-15", severity: "moderate", ageGroup: "15-44" },
  { id: "DS-003", city: "Mumbai", state: "Maharashtra", lat: 19.076, lng: 72.877, disease: "Leptospirosis", cases: 56, deaths: 2, date: "2024-01-10", severity: "moderate", ageGroup: "25-54" },
  // Delhi
  { id: "DS-004", city: "Delhi", state: "Delhi", lat: 28.679, lng: 77.213, disease: "Dengue", cases: 312, deaths: 4, date: "2024-01-15", severity: "high", ageGroup: "15-44" },
  { id: "DS-005", city: "Delhi", state: "Delhi", lat: 28.679, lng: 77.213, disease: "Chikungunya", cases: 189, deaths: 0, date: "2024-01-12", severity: "moderate", ageGroup: "25-54" },
  { id: "DS-006", city: "Delhi", state: "Delhi", lat: 28.679, lng: 77.213, disease: "Typhoid", cases: 94, deaths: 1, date: "2024-01-08", severity: "moderate", ageGroup: "5-24" },
  // Bangalore
  { id: "DS-007", city: "Bangalore", state: "Karnataka", lat: 12.971, lng: 77.594, disease: "Dengue", cases: 178, deaths: 2, date: "2024-01-14", severity: "high", ageGroup: "15-44" },
  { id: "DS-008", city: "Bangalore", state: "Karnataka", lat: 12.971, lng: 77.594, disease: "H1N1 Influenza", cases: 67, deaths: 1, date: "2024-01-11", severity: "moderate", ageGroup: "0-14" },
  // Chennai
  { id: "DS-009", city: "Chennai", state: "Tamil Nadu", lat: 13.083, lng: 80.27, disease: "Dengue", cases: 203, deaths: 3, date: "2024-01-15", severity: "high", ageGroup: "15-44" },
  { id: "DS-010", city: "Chennai", state: "Tamil Nadu", lat: 13.083, lng: 80.27, disease: "Cholera", cases: 34, deaths: 1, date: "2024-01-09", severity: "high", ageGroup: "all" },
  // Kolkata
  { id: "DS-011", city: "Kolkata", state: "West Bengal", lat: 22.573, lng: 88.364, disease: "Malaria", cases: 156, deaths: 2, date: "2024-01-15", severity: "high", ageGroup: "15-44" },
  { id: "DS-012", city: "Kolkata", state: "West Bengal", lat: 22.573, lng: 88.364, disease: "Kala Azar", cases: 23, deaths: 0, date: "2024-01-13", severity: "moderate", ageGroup: "25-54" },
  // Pune
  { id: "DS-013", city: "Pune", state: "Maharashtra", lat: 18.52, lng: 73.855, disease: "Dengue", cases: 134, deaths: 1, date: "2024-01-14", severity: "moderate", ageGroup: "15-44" },
  { id: "DS-014", city: "Pune", state: "Maharashtra", lat: 18.52, lng: 73.855, disease: "Typhoid", cases: 78, deaths: 0, date: "2024-01-10", severity: "low", ageGroup: "5-24" },
  // Hyderabad
  { id: "DS-015", city: "Hyderabad", state: "Telangana", lat: 17.385, lng: 78.487, disease: "Dengue", cases: 167, deaths: 2, date: "2024-01-15", severity: "high", ageGroup: "15-44" },
  { id: "DS-016", city: "Hyderabad", state: "Telangana", lat: 17.385, lng: 78.487, disease: "Malaria", cases: 89, deaths: 1, date: "2024-01-12", severity: "moderate", ageGroup: "25-54" },
  // Jaipur
  { id: "DS-017", city: "Jaipur", state: "Rajasthan", lat: 26.912, lng: 75.787, disease: "Malaria", cases: 112, deaths: 1, date: "2024-01-15", severity: "moderate", ageGroup: "15-44" },
  { id: "DS-018", city: "Jaipur", state: "Rajasthan", lat: 26.912, lng: 75.787, disease: "Typhoid", cases: 67, deaths: 0, date: "2024-01-11", severity: "low", ageGroup: "5-24" },
  // Ahmedabad
  { id: "DS-019", city: "Ahmedabad", state: "Gujarat", lat: 23.023, lng: 72.571, disease: "Dengue", cases: 98, deaths: 1, date: "2024-01-14", severity: "moderate", ageGroup: "15-44" },
  { id: "DS-020", city: "Ahmedabad", state: "Gujarat", lat: 23.023, lng: 72.571, disease: "Chikungunya", cases: 45, deaths: 0, date: "2024-01-08", severity: "low", ageGroup: "25-54" },
  // Lucknow
  { id: "DS-021", city: "Lucknow", state: "Uttar Pradesh", lat: 26.847, lng: 80.947, disease: "Encephalitis", cases: 78, deaths: 8, date: "2024-01-15", severity: "critical", ageGroup: "0-14" },
  { id: "DS-022", city: "Lucknow", state: "Uttar Pradesh", lat: 26.847, lng: 80.947, disease: "Dengue", cases: 134, deaths: 2, date: "2024-01-12", severity: "high", ageGroup: "15-44" },
  // Patna
  { id: "DS-023", city: "Patna", state: "Bihar", lat: 25.594, lng: 85.137, disease: "Encephalitis", cases: 45, deaths: 6, date: "2024-01-15", severity: "critical", ageGroup: "0-14" },
  { id: "DS-024", city: "Patna", state: "Bihar", lat: 25.594, lng: 85.137, disease: "Kala Azar", cases: 34, deaths: 1, date: "2024-01-10", severity: "moderate", ageGroup: "25-54" },
  // Bhopal
  { id: "DS-025", city: "Bhopal", state: "Madhya Pradesh", lat: 23.259, lng: 77.413, disease: "Malaria", cases: 89, deaths: 1, date: "2024-01-14", severity: "moderate", ageGroup: "15-44" },
];

// Disease trends over time
export const diseaseTrends = [
  { month: "Aug", dengue: 234, malaria: 156, typhoid: 89, cholera: 12, chikungunya: 67 },
  { month: "Sep", dengue: 312, malaria: 189, typhoid: 112, cholera: 18, chikungunya: 89 },
  { month: "Oct", dengue: 489, malaria: 234, typhoid: 134, cholera: 23, chikungunya: 123 },
  { month: "Nov", dengue: 567, malaria: 267, typhoid: 156, cholera: 28, chikungunya: 145 },
  { month: "Dec", dengue: 445, malaria: 212, typhoid: 123, cholera: 19, chikungunya: 112 },
  { month: "Jan", dengue: 389, malaria: 178, typhoid: 98, cholera: 15, chikungunya: 89 },
];

// Age group distribution
export const ageGroupData = [
  { group: "0-14", dengue: 89, malaria: 123, typhoid: 156, total: 368 },
  { group: "15-24", dengue: 234, malaria: 178, typhoid: 134, total: 546 },
  { group: "25-44", dengue: 312, malaria: 201, typhoid: 145, total: 658 },
  { group: "45-64", dengue: 189, malaria: 134, typhoid: 98, total: 421 },
  { group: "65+", dengue: 78, malaria: 67, typhoid: 45, total: 190 },
];

// Hospital resources
export const hospitalResources = [
  { hospital: "Apollo Hospitals", city: "Hyderabad", totalBeds: 450, occupied: 312, icu: 40, icuOccupied: 28, ventilators: 25, ventilatorsOccupied: 18, doctors: 89, nurses: 234 },
  { hospital: "AIIMS Delhi", city: "Delhi", totalBeds: 2500, occupied: 2180, icu: 120, icuOccupied: 108, ventilators: 80, ventilatorsOccupied: 65, doctors: 456, nurses: 1234 },
  { hospital: "KEM Hospital", city: "Mumbai", totalBeds: 1800, occupied: 1456, icu: 90, icuOccupied: 78, ventilators: 60, ventilatorsOccupied: 48, doctors: 234, nurses: 678 },
  { hospital: "Manipal Hospital", city: "Bangalore", totalBeds: 650, occupied: 489, icu: 55, icuOccupied: 42, ventilators: 35, ventilatorsOccupied: 25, doctors: 112, nurses: 312 },
  { hospital: "CMC Vellore", city: "Chennai", totalBeds: 2700, occupied: 2234, icu: 130, icuOccupied: 115, ventilators: 85, ventilatorsOccupied: 72, doctors: 512, nurses: 1456 },
];

// Health alerts
export const healthAlerts = [
  { id: "ALT-001", title: "Dengue Outbreak - Mumbai", severity: "high", location: "Mumbai, Maharashtra", date: "2024-01-15", description: "245 new dengue cases reported in Dharavi and Kurla areas. Citizens advised to prevent mosquito breeding.", status: "active" },
  { id: "ALT-002", title: "Encephalitis Alert - UP/Bihar", severity: "critical", location: "Lucknow & Patna", date: "2024-01-15", description: "123 encephalitis cases with 14 deaths reported. Pediatric hospitals on high alert.", status: "active" },
  { id: "ALT-003", title: "Cholera Advisory - Chennai", severity: "high", location: "Chennai, Tamil Nadu", date: "2024-01-09", description: "34 cholera cases near Perambur. Water purification strictly advised.", status: "active" },
  { id: "ALT-004", title: "H1N1 Surveillance - Bangalore", severity: "moderate", location: "Bangalore, Karnataka", date: "2024-01-11", description: "Elevated H1N1 activity in Whitefield and Electronic City. Vaccination recommended.", status: "monitoring" },
  { id: "ALT-005", title: "Malaria Season Alert", severity: "moderate", location: "Eastern India", date: "2024-01-01", description: "Annual monsoon season malaria prevention measures initiated across 5 states.", status: "resolved" },
];

// Health expenses
export const healthExpenses = [
  { month: "Aug 2023", consultation: 1600, medicines: 2340, labTests: 1200, hospitalization: 0, total: 5140 },
  { month: "Sep 2023", consultation: 800, medicines: 1890, labTests: 800, hospitalization: 0, total: 3490 },
  { month: "Oct 2023", consultation: 800, medicines: 2100, labTests: 0, hospitalization: 0, total: 2900 },
  { month: "Nov 2023", consultation: 2300, medicines: 1800, labTests: 3400, hospitalization: 0, total: 7500 },
  { month: "Dec 2023", consultation: 800, medicines: 1900, labTests: 0, hospitalization: 45000, total: 47700 },
  { month: "Jan 2024", consultation: 2300, medicines: 2200, labTests: 2800, hospitalization: 0, total: 7300 },
];

// Vitals tracking
export const vitalsHistory = [
  { date: "Jan 1", systolic: 148, diastolic: 92, heartRate: 78, glucose: 145, weight: 84 },
  { date: "Jan 5", systolic: 145, diastolic: 90, heartRate: 76, glucose: 138, weight: 83.5 },
  { date: "Jan 10", systolic: 142, diastolic: 88, heartRate: 75, glucose: 132, weight: 83 },
  { date: "Jan 15", systolic: 140, diastolic: 86, heartRate: 74, glucose: 128, weight: 82.8 },
  { date: "Jan 20", systolic: 138, diastolic: 85, heartRate: 74, glucose: 124, weight: 82.5 },
  { date: "Jan 25", systolic: 136, diastolic: 84, heartRate: 73, glucose: 120, weight: 82 },
  { date: "Feb 1", systolic: 134, diastolic: 83, heartRate: 72, glucose: 118, weight: 81.8 },
];

export const drugDatabase = [
  { name: "Amlodipine", category: "Antihypertensive", dosages: ["2.5mg", "5mg", "10mg"], interactions: ["Simvastatin", "Cyclosporine"] },
  { name: "Metformin", category: "Antidiabetic", dosages: ["500mg", "850mg", "1000mg"], interactions: ["Alcohol", "Iodinated contrast"] },
  { name: "Aspirin", category: "Antiplatelet/Analgesic", dosages: ["75mg", "150mg", "325mg"], interactions: ["Warfarin", "Ibuprofen", "Heparin"] },
  { name: "Atorvastatin", category: "Statin", dosages: ["10mg", "20mg", "40mg", "80mg"], interactions: ["Cyclosporine", "Erythromycin", "Niacin"] },
  { name: "Lisinopril", category: "ACE Inhibitor", dosages: ["5mg", "10mg", "20mg"], interactions: ["Potassium", "NSAIDs", "Lithium"] },
  { name: "Azithromycin", category: "Antibiotic", dosages: ["250mg", "500mg"], interactions: ["Warfarin", "Digoxin", "Antacids"] },
  { name: "Paracetamol", category: "Analgesic", dosages: ["325mg", "500mg", "650mg"], interactions: ["Warfarin", "Alcohol"] },
  { name: "Omeprazole", category: "PPI", dosages: ["10mg", "20mg", "40mg"], interactions: ["Clopidogrel", "Methotrexate"] },
];
